### Home
GET {{url}}{{module-users}}
Accept: application/json

### Get account
GET {{url}}{{module-users}}/account
Accept: application/json
Authorization: Bearer {{token}}

### Sign up
POST {{url}}{{module-users}}/account/sign-up
Content-Type: application/json

{
  "email": "user@moneyme.com",
  "password": "secret",
  "role": "user",
  "claims": {
    "permissions": ["investments", "components", "users", "categories", "expenses", "incomes"]
  }
}

### Sign in
POST {{url}}{{module-users}}/account/sign-in
Content-Type: application/json

{
  "email": "user@moneyme.com",
  "password": "secret"
}