### Home
GET {{url}}{{module-investments}}
Accept: application/json

### Create investment component
POST {{url}}{{module-investments}}/investmentcomponents
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "abc",
  "investmentId": "a603162a-7741-43d2-8913-1fd70447224f",
  "description": "test 233",
  "type": 1
}

> {%
    client.test("Location exists", function() {
        client.assert(response.headers.valueOf("Location") !== undefined, "Cannot find 'location' in response");
    });
    
    client.global.set("investmentComponentUrl", response.headers.valueOf("Location"));
%}

### Get created investment component
GET {{investmentComponentUrl}}
Accept: application/json
Authorization: Bearer {{token}}

### Get all investment components
GET {{url}}{{module-investments}}/investmentcomponents
Accept: application/json
Authorization: Bearer {{token}}

### Get investment component by id
GET {{url}}{{module-investments}}/investmentcomponents/6279b8ba-6079-4b22-9724-94a0ecb56f97
Accept: application/json
Authorization: Bearer {{token}}

### Update investment component
PUT {{url}}{{module-investments}}/investmentcomponents/6279b8ba-6079-4b22-9724-94a0ecb56f97
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "abcd",
  "investmentId": "becec694-2840-485a-aab0-6f915347f9d1",
  "type": 2
  
}

### Delete investment component
DELETE {{url}}{{module-investments}}/investmentcomponents/6279b8ba-6079-4b22-9724-94a0ecb56f97
Accept: application/json
Authorization: Bearer {{token}}
