### Home
GET {{url}}{{module-investments}}
Accept: application/json

### Add investment contributor
POST {{url}}{{module-investments}}/investmentcontributors
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "investmentComponentId": "b3d593f3-384d-4e12-a1a9-5c4692ea4c36",
  "investmentContributorId": "a82e1993-b458-44aa-8967-069e5b0380f4",
  "role": 1
}

### Get all contributors for investment component
GET {{url}}{{module-investments}}/investmentcontributors/aaaa
Accept: application/json
Authorization: Bearer {{token}}

### Delete investment contributor
DELETE {{url}}{{module-investments}}/investmentcontributors/aaa
Accept: application/json
Authorization: Bearer {{token}}
